-- ============================================================================
-- CI Test Seed Data
-- ----------------------------------------------------------------------------
-- All seeding is done via the GitHub Actions workflow (integration-tests.yml)
-- AFTER GoTrue creates auth users via Admin API. This file is intentionally
-- empty because all tables have FK dependencies on auth.users.
-- ============================================================================
